AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for S3 infrastructure"

Parameters:
  Environment:
    Type: String
    Description: "The environment for the S3 bucket (e.g., dev, prod)"
    Default: "dev"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Sub: "${Environment}-my-s3-bucket-229944035544"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true