AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template for network infrastructure"

Parameters: 
   Environment:
      Type: String
      Description: "Environment name (e.g., dev, prod)"
    
   VpcCidrBlock:
      Type: String
      Description: "CIDR block for the VPC"
      
Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: !Ref VpcCidrBlock
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value:
              Fn::Sub : "${Environment}-vpc"

      