AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template for network infrastructure with workflow helpers"

Parameters: 
   Environment:
      Type: String
      Description: "Environment name (e.g., dev, prod)"

Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: "10.0.0.0/16"
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value:
              Fn::Sub : "my-vpc-${Environment}"